export const metadata = {
    title: "about",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <>
            {/* it is the main body part so we can add navbar and footer here */}
            <div>it is dummy navbar for about page</div>
            {children}
            <div>it is dummy footer for about but it will ested like it</div>
        </>
    );

}
